package com.chrynan.graphkl.validation

enum class SdlRule : ValidationRule {

    LONE_SCHEMA_DEFINITION,
    UNIQUE_OPERATION_TYPES,
    UNIQUE_TYPE_NAMES,
    UNIQUE_ENUM_VALUE_NAMES,
    UNIQUE_FIELD_DEFINITION_NAMES,
    UNIQUE_DIRECTIVE_NAMES,
    KNOWN_TYPE_NAMES,
    KNOWN_DIRECTIVES,
    UNIQUE_DIRECTIVES_PER_LOCATION,
    POSSIBLE_TYPE_EXTENSIONS,
    KNOWN_ARGUMENT_NAMES_ON_DIRECTIVES,
    UNIQUE_ARGUMENT_NAMES,
    UNIQUE_INPUT_FIELD_NAMES,
    PROVIDED_REQUIRED_ARGUMENTS_ON_DIRECTIVES
}